using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._SIS.Respawn.UI;

[GenerateTypedNameReferences]
public sealed partial class RespawnWindow : DefaultWindow
{
    public event Action? OnRequestPressed;

    public RespawnWindow()
    {
        RobustXamlLoader.Load(this);

        RequestButton.OnPressed += _ => OnRequestPressed?.Invoke();
    }
}
