<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>..\bin\Content.Server\</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <NoWarn>1998</NoWarn>
    <WarningsAsErrors>RA0032;nullable</WarningsAsErrors>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <Import Project="../MSBuild/Content.props" />
  <Import Project="..\RobustToolbox\MSBuild\Robust.Properties.targets" />

  <ItemGroup>
    <ProjectReference Include="..\Content.Server.Database\Content.Server.Database.csproj" />
    <ProjectReference Include="..\Content.Shared.Database\Content.Shared.Database.csproj" />
    <ProjectReference Include="..\Content.Server\Content.Server.csproj" />
    <ProjectReference Include="..\Content.Shared\Content.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Content.ModuleManager\Content.ModuleManager.csproj" />
    <ProjectReference Include="..\Content.Goobstation.Maths\Content.Goobstation.Maths.csproj" />
    <ProjectReference Include="..\Content.Goobstation.Shared\Content.Goobstation.Shared.csproj" />
  </ItemGroup>
</Project>
